name: Build¥

on:
  pull_request:
    branches-ignore:
      - "renovate/**"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: docker-cache/src
          key: v1-${{ hashFiles('./Dockerfile') }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            v1-${{ hashFiles('./Dockerfile') }}-${{ github.ref }}-
            v1-${{ hashFiles('./Dockerfile') }}-
            v1-
      - name: Build docker container
        run: |
          docker buildx create --use
          docker buildx build --tag rinsuki/sakvas:latest --cache-from=type=local,src=./docker-cache/src --cache-to=type=local,dest=./docker-cache/dest,mode=max --load .
          cd docker-cache && mv src old && mv dest src && rm -rf old
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
      - name: Upload docker image
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          python3 -c 'import os;print(os.getenv("DOCKERHUB_TOKEN"), end="")' | docker login --username rinsuki --password-stdin
          docker push rinsuki/sakvas:latest
          docker logout
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
